### PR TITLE
fixed memory leak issue / remove resize event

### PR DESCRIPTION
**Pull request by mrdivyansh**
Fixed [Issue #16](https://github.com/whoisandie/react-rangeslider/issues/16)

### CODE REVIEW

**Comment by mrdivyansh** [comment]
@whoisandie: I am waiting for your response.

**Comment by whoisandie** [comment]
@mrdivyansh Thx 👍

**Comment by whoisandie** [comment]
@mrdivyansh @pabloen @TylerU Fixed 👍

**Comment by whoisandie** [comment]
@mrdivyansh @pabloen @TylerU Fixed! 👍

**Pull request merged**
