### PR TITLE
#35 Range slider's css remove from example. Then css is added to sour…

### PR DESCRIPTION
**Pull request by mahmutduva**
…ce code

### CODE REVIEW

**Comment by whoisandie** [comment]
@mahmutduva Looks like the branch has conflicts, could you please resolve them and make a PR?

**Comment by mahmutduva** [comment]
@whoisandie I resolved conflicts, you can check it.

**Comment by whoisandie** [comment]
@mahmutduva 👍

**Comment by mvatansever** [comment]
Congratulations @mahmutduva now you have access to go America!

**Pull request merged**
